apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: airflow-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - airflow-staging.gitlabdata.com
    secretName: airflow-tls
  rules:
  - host: airflow-staging.gitlabdata.com
    http:
      paths:
      - path: /
        backend:
          serviceName: airflow-webserver
          servicePort: 8080